version: "3.3"

services:
  web:
    build:
      context: web
      dockerfile: web.Dockerfile
    ports:
      - "8000:80"

  api:
    build:
      context: api
      dockerfile: api.Dockerfile
    ports:
      - "8001:8001"
